server:
  port: 9002

mq:
  worker:
    queue-name: worker
    concurrency: 1-1
    message-type-id: org.gol.taskmanager.infrastructure.amq.AmqWorkerMessage

spring:
  activemq:
    broker-url: failover:(tcp://localhost:61616)?jms.useAsyncSend=true
    user: admin
    password: admin

logging:
  level:
    org.gol: trace