server:
  port: ${TOMCAT_PORT:8080}

mq:
  worker:
    queue-name: ${WORKER_QUEUE_NAME}
    concurrency: ${WORKER_CONCURRENCY:1-10}
    message-type-id: ${WORKER_MESSAGE_TYPE_ID:org.gol.taskmanager.infrastructure.amq.AmqWorkerMessage}

spring:
  # Artemis broker
  artemis:
    mode: native
    broker-url: ${BROKER_URL}
    user: ${BROKER_USER}
    password: ${BROKER_PASSWORD}
  jms:
    cache:
      session-cache-size: ${JMS_SESSION_CACHE_SIZE:5}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: ping
        readiness:
          include: jms, diskSpace

logging:
  level:
    root: info
    org.gol: ${LOGGING_LEVEL:info}