mq:
  worker:
    queue-name: ${WORKER_QUEUE_NAME}
    concurrency: ${WORKER_CONCURRENCY}
    message-type-id: ${WORKER_MESSAGE_TYPE_ID:org.gol.taskmanager.infrastructure.amq.AmqWorkerMessage}

spring:
  # ActiveMQ broker
  activemq:
    broker-url: ${BROKER_URL}
    user: ${BROKER_USER}
    password: ${BROKER_PASSWORD}

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
    org.gol: ${LOGGING_LEVEL}