mq:
  worker:
    queue-name: worker
    concurrency: 1-1
    message-type-id: org.gol.taskmanager.infrastructure.amq.AmqWorkerMessage

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

logging:
  level:
    org.gol: trace